version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/resume-app
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/beforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterInstall.sh
      timeout: 300
      runas: root
